### PR TITLE
Run bash script in strict mode

### PR DESCRIPTION
**Pull request by davetcoleman**
- Improves code quality

### CODE REVIEW

**Comment by davetcoleman** [comment]
@rhaschke I started this effort but have not finished. A good practice in writing bash scripts is to enable strict mode (variables must be initialized):

> #!/bin/bash -eu

However I'm finding you use ``unset`` a lot through the code, so I'd like to get your thoughts first before I continue this effort.

**Comment by rhaschke** [comment]
@davetcoleman, I agree, that enabling unbound variable checking (option `-u`) might be useful. I fixed and continued your changes as far as possible for now.
Enabling option `-e` requires a lot more effort, because we cannot use `$?` anymore to evaluate the result of a previous command. However, this is heavily used throughout the scripts.

**Comment by v4hn** [comment]
> Enabling option `-e` requires a lot more effort

`-e` might sound good at first glance, but usually produces many problems.
return codes do not just indicate critical failure in most scripts.
I do not believe it is a good idea to require it.

**Comment by rhaschke** [comment]
Replaced with rebase in #74 to fix merge conflicts and finish development.

**Comment by davetcoleman** [comment]
Thanks!

**Pull request closed without merging**
